spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_name
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    default-encoding: UTF-8
    port: 587
    username: <yourusername>
    password: <yourpassword>
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
server:
  port: 8081